# Workaround for Dependabot - https://github.com/dependabot/dependabot-core/issues/390
FROM leastauthority/magic-wormhole-relay:25.9.1@sha256:e1b3ce5a820a085714a63c701b14d27ac4d2e364c98c6976aafb51b8eae088b7
