name: 'Magic Wormhole Secret'
description: 'Transfer secret via Magic Wormhole'
inputs:
  code:
    description: 'Code to receive the secret'
    required: true
  path:
    description: 'Path to receive the secret'
    required: true
  mailbox:
    description: 'Mailbox server'
    required: true
    default: wss://mailbox.mw.leastauthority.com/v1
  transit:
    description: 'Transit server'
    required: true
    default: tcp://relay.mw.leastauthority.com:4001
outputs:
  result:
    description: 'stderr of the wormhole command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --relay-url
    - ${{ inputs.mailbox }}
    - --transit-helper
    - ${{ inputs.transit }}
    - receive
    - --hide-progress
    - --accept-file
    - --output-file
    - ${{ inputs.path }}
    - ${{ inputs.code }}
