name: 'Setup Docker Image'
description: 'Prepare Docker and build an image ready to be run using the composer'
inputs:
  service_name:
    description: 'Name of the service to prepare in the docker-compose.yml'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache image
      id: cache_image
      uses: AndreKurait/docker-cache@0.6.0
      with:
        key: |
          docker-${{ runner.os }}-${{ hashFiles(
            'docker-compose*.yml',
            'docker/${{ inputs.service_name }}/*'
          ) }}

    - name: Fix membership
      id: fix_membership
      run: |
        # Add the existing `runner` group to avoid the `docker` one,
        # so we can consume this non-privilege gid as a build-arg later
        sudo adduser runner runner
        echo "_GID=$(grep -E "^runner:" /etc/group | cut -d: -f3)" >> $GITHUB_ENV
      shell: bash

    - name: Build image
      id: build_image
      run: |
        docker images "*${{ inputs.service_name }}"
        repository=${{ github.repository }}
        # Build the image only if it was not restored from the cache
        docker images --quiet ${repository##*/}*${{ inputs.service_name }}:latest | grep -v "^$" || \
        docker compose --progress=plain build \
        --build-arg uid=$(id -u) \
        --build-arg gid=${_GID} \
        ${{ inputs.service_name }} && \
        docker images "*${{ inputs.service_name }}"
      shell: bash
