version: "3.3"
services:
  traefik:
    build:
      context: ./docker/traefik
    command:
      - "--accesslog"
      - "--metrics.datadog=true"
      - "--metrics.datadog.address=172.18.0.1:8125"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.webtls.address=:443"
      - "--entrypoints.mailbox_ws.address=:4000"
      - "--entrypoints.relay_tcp.address=:4001"
      - "--entrypoints.relay_ws.address=:4002"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=mwaws@leastauthority.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  mailbox:
    build:
      context: ./docker/mailbox
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailbox.rule=Host({{ '`' + mailbox_hosts|join('`,`') + '`' }})"
      - "traefik.http.routers.mailbox.entrypoints=web"
      - "traefik.http.routers.mailbox.service=mailbox-service"
      - "traefik.http.routers.mailbox_tls.rule=Host({{ '`' + mailbox_hosts|join('`,`') + '`' }})"
      - "traefik.http.routers.mailbox_tls.tls.certresolver=le"
      - "traefik.http.routers.mailbox_tls.entrypoints=webtls"
      - "traefik.http.routers.mailbox_tls.service=mailbox-service"
      - "traefik.http.routers.mailbox_ws.rule=HostRegexp(`{catchall:.*}`)"
      - "traefik.http.routers.mailbox_ws.entrypoints=mailbox_ws"
      - "traefik.http.routers.mailbox_ws.service=mailbox-service"
      - "traefik.http.services.mailbox-service.loadbalancer.server.port=4000"
    volumes:
      - "./mailbox_database:/db"
  relay:
    build:
      context: ./docker/relay
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.relay.rule=Host({{ '`' + transit_hosts|join('`,`') + '`' }})"
      - "traefik.http.routers.relay.entrypoints=web"
      - "traefik.http.routers.relay.service=relay_ws-service"
      - "traefik.http.routers.relay_tls.rule=Host({{ '`' + transit_hosts|join('`,`') + '`'}})"
      - "traefik.http.routers.relay_tls.tls.certresolver=le"
      - "traefik.http.routers.relay_tls.entrypoints=webtls"
      - "traefik.http.routers.relay_tls.service=relay_ws-service"
      - "traefik.tcp.routers.relay_tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.relay_tcp.entrypoints=relay_tcp"
      - "traefik.tcp.routers.relay_tcp.service=relay_tcp-service"
      - "traefik.http.routers.relay_ws.rule=HostRegexp(`{catchall:.*}`)"
      - "traefik.http.routers.relay_ws.entrypoints=relay_ws"
      - "traefik.http.routers.relay_ws.service=relay_ws-service"
      - "traefik.tcp.services.relay_tcp-service.loadbalancer.server.port=4001"
      - "traefik.http.services.relay_ws-service.loadbalancer.server.port=4002"
    volumes:
      - "./relay_database:/db"
  feedback:
    build:
      context: ./docker/feedback
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "256m"
    environment:
      - SMTP_HELO={{ feedback_hosts[0] }}
      - SMTP_SERVER=aspmx.l.google.com
      - SMTP_PORT=25
      - SMTP_USERNAME=feedback # Only to avoid warning when auth. is not required
      - SMTP_PASSWORD=xxx      # TODO: Remove user/pass when upstream is ready
      - SMTP_USE_TLS=false
      - SMTP_USE_INSECURE_TLS=false
      - SMTP_FROM={{ feedback_from_addr }}
      - SMTP_TO={{ feedback_to_addr }}
      - HTTP_PORT=8001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedback.rule=Host({{ '`' + feedback_hosts|join('`,`') + '`' }})"
      - "traefik.http.routers.feedback.entrypoints=web"
      - "traefik.http.routers.feedback.service=feedback-service"
      - "traefik.http.routers.feedback_tls.rule=Host({{ '`' + feedback_hosts|join('`,`') + '`'}})"
      - "traefik.http.routers.feedback_tls.tls.certresolver=le"
      - "traefik.http.routers.feedback_tls.entrypoints=webtls"
      - "traefik.http.routers.feedback_tls.service=feedback-service"
      - "traefik.http.routers.feedback.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.services.feedback-service.loadbalancer.server.port=8001"
