# Workaround for Dependabot - https://github.com/dependabot/dependabot-core/issues/390
FROM leastauthority/magic-wormhole-mailbox:23.5.0@sha256:595d7c30ba0edb7f679e3deaa370bfa5dcc05219aaed8cf16a0c6ac407944909
