# Workaround for Dependabot - https://github.com/dependabot/dependabot-core/issues/390
FROM leastauthority/magic-wormhole-mailbox:25.9.1@sha256:78b49fddc9fabd6d496076105a944de0ec5af74c64c4e036a1a2b89584fd421b
