# Workaround for Dependabot - https://github.com/dependabot/dependabot-core/issues/390
FROM leastauthority/feedback-http-server:0.1.3@sha256:6e007767aa5201c22eb8988a48ab9e04022cbe14c087ec7b48ea097f69244fa4
