name: Updates
on:
  schedule:
    - cron: "27 4 * * 1"
  workflow_dispatch:

jobs:
  ansible:
    name: Ansible
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Prepare Ansible
        id: prepare_ansible
        uses: la-test/.github/actions/setup-docker-image@6660d3dbacedb09cca8f8a04294fe4c2658a50bc
        with:
          service-name: ansible-controller

      - name: Update requirements
        id: update_requirements
        run: |
          docker compose run --rm \
          ansible-controller bash -e << EOC
            # Upgrade the main packages
            pip install --upgrade --upgrade-strategy eager ansible ansible-lint
            # Save the new requirements
            python3 -m pip freeze --local > ../docker/ansible/requirements.txt
            # Reinstall the new requirements to be safe
            pip install --force-reinstall -r ../docker/ansible/requirements.txt
            # Some sanity checks
            python3 -m pip check
            ansible-playbook --version
            ansible-lint --version
          EOC

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            docker/ansible/requirements.txt
          base: "main"
          branch: "updates/ansible"
          commit-message: "Update Ansible and its dependencies"
          delete-branch: true
          title: "Update Ansible and its dependencies"
          token: ${{ secrets.GH_PAT_UPDATE }}
